# Generated by Django 4.0 on 2021-12-16 23:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_options_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='user-default.png', max_length=255, verbose_name='image'),
        ),
    ]
