# Generated by Django 4.0 on 2021-12-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_tag_blog_vote_ratio_blog_vote_total_review_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
