# Generated by Django 4.0 on 2021-12-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_intro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
