# Generated by Django 4.0 on 2021-12-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_location_alter_profile_short_intro'),
        ('blogs', '0005_blog_short_intro_alter_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='project',
            new_name='blog',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'blog')},
        ),
    ]
