# Generated by Django 4.0 on 2021-12-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_options_rename_project_review_blog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['vote_ratio', '-vote_total', '-created']},
        ),
    ]
