# Generated by Django 4.0 on 2021-12-17 23:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/mistakes/image/upload/v1639782182/mistakes/user-images/default_wwv4ka.jpg', max_length=255, verbose_name='image'),
        ),
    ]
